version: '3'
services:
  nginx-php7:
    image: skiychan/nginx-php7:latest
    ports:
      - "38080:80"
    volumes:
      - ./www:/data/wwwroot
      - ./vhost:/usr/local/nginx/conf/vhost
      - ./wwwlogs:/data/wwwlogs